In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2022-ai-w5p1/train.csv
/kaggle/input/2022-ai-w5p1/test.csv
/kaggle/input/2022-ai-w5p1/sample_submit.csv


In [2]:
import random
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True

# 데이터 불러오기

In [3]:
train = pd.read_csv('../input/2022-ai-w5p1/train.csv')
train

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          5    0    0    0    0    0    0    0    0    0  ...      0      0   
1          0    0    0    0    0    0    0    0    0    0  ...      0      0   
2          3    0    0    0    0    0    0    0    0    0  ...      0      0   
3          3    0    0    0    0    0    0    0    0    0  ...      0      0   
4          6    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
59995      0    0    0    0    0    0    0    0    0    0  ...      0      0   
59996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
59997      9    0    0    0    0    0    0    0    0    0  ...      0      0   
59998      4    0    0    0    0    0    0    0    0    0  ...      0      0   
59999      6    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 785 columns]

In [4]:
X_train = train.iloc[:,1:]
y_train = train.iloc[:,0]

In [5]:
X_train

1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  1x10  ...  28x19  28x20  \
0        0    0    0    0    0    0    0    0    0     0  ...      0      0   
1        0    0    0    0    0    0    0    0    0     0  ...      0      0   
2        0    0    0    0    0    0    0    0    0     0  ...      0      0   
3        0    0    0    0    0    0    0    0    0     0  ...      0      0   
4        0    0    0    0    0    0    0    0    0     0  ...      0      0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...    ...    ...   
59995    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59996    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59997    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59998    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59999    0    0    0    0    0    0    0    0    0     0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 784 columns]

In [6]:
y_train

0        5
1        0
2        3
3        3
4        6
        ..
59995    0
59996    3
59997    9
59998    4
59999    6
Name: label, Length: 60000, dtype: int64

## 데이터 정규화

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## 데이터 형변환

In [8]:
X_train = torch.Tensor(X_train)
X_train

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [9]:
y_train = torch.LongTensor(y_train)
y_train

tensor([5, 0, 3,  ..., 9, 4, 6])

In [10]:
print(X_train.shape)
print(y_train.shape)

torch.Size([60000, 784])
torch.Size([60000])


# 선형 분류 모델 

In [11]:
W = torch.zeros([784, 10],requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.Adam([W,b])

nb_epochs = 2000
for epoch in range(nb_epochs+1):
    
    #H(x) 계산
    hypothesis = F.softmax(X_train.matmul(W)+b,dim=1)
    
    #cost 계산
    cost = F.cross_entropy(X_train.matmul(W)+b, y_train)
    
    #cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    
    if epoch%1000 == 0:
        print('Epoch: {:4d}/{}  Cost:{:.6f}'.format(
        epoch, nb_epochs, cost.item()
        ))

Epoch:    0/2000  Cost:2.302585
Epoch: 1000/2000  Cost:0.287177
Epoch: 2000/2000  Cost:0.254397


In [12]:
#성능 평가하기
hypothesis = F.softmax(X_train.matmul(W)+b,dim=1)
prediction = torch.argmax(hypothesis,dim=1)
correct_prediction = (y_train == prediction).sum() / len(y_train)

print('accuarcy: {:.6f}%'.format(correct_prediction*100))

accuarcy: 93.021667%


# 테스트 데이터 불러오기

In [13]:
X_test = pd.read_csv('../input/2022-ai-w5p1/test.csv')
X_test

1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  1x10  ...  28x19  28x20  \
0       0    0    0    0    0    0    0    0    0     0  ...      0      0   
1       0    0    0    0    0    0    0    0    0     0  ...      0      0   
2       0    0    0    0    0    0    0    0    0     0  ...      0      0   
3       0    0    0    0    0    0    0    0    0     0  ...      0      0   
4       0    0    0    0    0    0    0    0    0     0  ...      0      0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...    ...    ...   
9995    0    0    0    0    0    0    0    0    0     0  ...      0      0   
9996    0    0    0    0    0    0    0    0    0     0  ...      0      0   
9997    0    0    0    0    0    0    0    0    0     0  ...      0      0   
9998    0    0    0    0    0    0    0    0    0     0  ...      0      0   
9999    0    0    0    0    0    0    0    0    0     0  ...      0      0   

      28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0         0      0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...    ...  
9995      0      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0      0  
9999      0      0      0      0      0      0      0      0  

[10000 rows x 784 columns]

## 데이터 정규화

In [14]:
X_test = scaler.transform(X_test)
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
X_test = torch.FloatTensor(X_test)
X_test

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [16]:
hypothesis2 = F.softmax(X_test.matmul(W)+b,dim = 1)
prediction2 = torch.argmax(hypothesis2,dim=1)
prediction2

tensor([6, 1, 0,  ..., 2, 8, 3])

# 제출용 파일 불러오기

In [17]:
submit = pd.read_csv('../input/2022-ai-w5p1/sample_submit.csv')
submit

id  label
0         1    NaN
1         2    NaN
2         3    NaN
3         4    NaN
4         5    NaN
...     ...    ...
9995   9996    NaN
9996   9997    NaN
9997   9998    NaN
9998   9999    NaN
9999  10000    NaN

[10000 rows x 2 columns]

In [18]:
submit['label'] = prediction2
submit

id  label
0         1      6
1         2      1
2         3      0
3         4      0
4         5      9
...     ...    ...
9995   9996      3
9996   9997      7
9997   9998      2
9998   9999      8
9999  10000      3

[10000 rows x 2 columns]

In [19]:
submit.to_csv('submit.csv',index = False)