In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2022-ai-w7p1/mnist_test.csv
/kaggle/input/2022-ai-w7p1/mnist_train.csv
/kaggle/input/2022-ai-w7p1/submission.csv


In [2]:
import random
import torch
import torch.nn as nn
import torch.optim as optim

seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True

In [3]:
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

# 데이터 전처리

## X_train, y_train, X_test

In [4]:
train = pd.read_csv('../input/2022-ai-w7p1/mnist_train.csv')
train

Unnamed: 0    0    1    2    3    4    5    6    7    8  ...  775  776  \
0               0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1               1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2               2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3               3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
4               4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...           ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995       59995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
59996       59996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
59997       59997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
59998       59998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
59999       59999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

       777  778  779  780  781  782  783  784  
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0  
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0  
...    ...  ...  ...  ...  ...  ...  ...  ...  
59995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  8.0  
59996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  3.0  
59997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0  
59998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  6.0  
59999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  8.0  

[60000 rows x 786 columns]

In [5]:
train = train.drop(['Unnamed: 0'],axis=1)
train

0    1    2    3    4    5    6    7    8    9  ...  775  776  777  \
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

       778  779  780  781  782  783  784  
0      0.0  0.0  0.0  0.0  0.0  0.0  5.0  
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  4.0  
3      0.0  0.0  0.0  0.0  0.0  0.0  1.0  
4      0.0  0.0  0.0  0.0  0.0  0.0  9.0  
...    ...  ...  ...  ...  ...  ...  ...  
59995  0.0  0.0  0.0  0.0  0.0  0.0  8.0  
59996  0.0  0.0  0.0  0.0  0.0  0.0  3.0  
59997  0.0  0.0  0.0  0.0  0.0  0.0  5.0  
59998  0.0  0.0  0.0  0.0  0.0  0.0  6.0  
59999  0.0  0.0  0.0  0.0  0.0  0.0  8.0  

[60000 rows x 785 columns]

In [6]:
X_train = train.iloc[:,:-1]
X_train

0    1    2    3    4    5    6    7    8    9  ...  774  775  776  \
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

       777  778  779  780  781  782  783  
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...    ...  ...  ...  ...  ...  ...  ...  
59995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
59996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
59997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
59998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
59999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[60000 rows x 784 columns]

In [7]:
y_train = train.iloc[:,-1]
y_train

0        5.0
1        0.0
2        4.0
3        1.0
4        9.0
        ... 
59995    8.0
59996    3.0
59997    5.0
59998    6.0
59999    8.0
Name: 784, Length: 60000, dtype: float64

In [8]:
X_test = pd.read_csv("../input/2022-ai-w7p1/mnist_test.csv")
X_test

Unnamed: 0    0    1    2    3    4    5    6    7    8  ...  774  775  \
0              0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1              1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2              2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3              3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
4              4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...          ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995        9995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
9996        9996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
9997        9997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
9998        9998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
9999        9999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

      776  777  778  779  780  781  782  783  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  
9995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[10000 rows x 785 columns]

In [9]:
X_test = X_test.drop(['Unnamed: 0'],axis=1)
X_test

0    1    2    3    4    5    6    7    8    9  ...  774  775  776  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      777  778  779  780  781  782  783  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
9995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[10000 rows x 784 columns]

## StandardScaler

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
X_test = scaler.fit_transform(X_test)
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## Tensor & GPU

In [12]:
X_train = torch.FloatTensor(X_train)
X_train

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [13]:
y_train = torch.LongTensor(y_train.to_numpy())
y_train

tensor([5, 0, 4,  ..., 5, 6, 8])

In [14]:
X_test = torch.FloatTensor(X_test)
X_test

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

## Shape

In [15]:
print(X_train.shape)
print(y_train.shape)

torch.Size([60000, 784])
torch.Size([60000])


## DataLoader

In [16]:
mnist_train = torch.utils.data.TensorDataset(X_train, y_train)
# mnist_test = torch.utils.data.TensorDataset(X_test)

In [17]:
data_loader_train = torch.utils.data.DataLoader(dataset=mnist_train,
                                          batch_size=50,
                                          shuffle=True,
                                          drop_last=True)

# data_loader_test = torch.utils.data.DataLoader(dataset=mnist_test,
#                                           batch_size=100,
#                                           shuffle=True,
#                                           drop_last=True)

# Model training

In [18]:
learning_rate = 0.0001
training_epochs = 100
#batch_size = 100
drop_prob = 0.3

In [19]:
linear1 = nn.Linear(784,1024)
linear2 = nn.Linear(1024,1024)
linear3 = nn.Linear(1024,1024)
linear4 = nn.Linear(1024,1024)
linear5 = nn.Linear(1024,10)
relu = nn.ReLU()
dropout = torch.nn.Dropout(p=drop_prob)

In [20]:
nn.init.xavier_normal_(linear1.weight)
nn.init.xavier_normal_(linear2.weight)
nn.init.xavier_normal_(linear3.weight)
nn.init.xavier_normal_(linear4.weight)
nn.init.xavier_normal_(linear5.weight)

Parameter containing:
tensor([[-0.0871,  0.0073, -0.0511,  ..., -0.0960, -0.0488, -0.0387],
        [ 0.0027,  0.0578, -0.0017,  ...,  0.0702, -0.0207, -0.0508],
        [-0.0347, -0.0060, -0.0013,  ...,  0.0117,  0.0207,  0.0293],
        ...,
        [-0.0536, -0.1042, -0.0395,  ...,  0.0176, -0.0844,  0.0172],
        [-0.0528, -0.0229, -0.0819,  ...,  0.0095,  0.0007,  0.0405],
        [-0.0288, -0.0490, -0.0025,  ..., -0.0170,  0.0643, -0.0169]],
       requires_grad=True)

In [21]:
model = nn.Sequential(linear1,relu,dropout,
                      linear2,relu,dropout,
                      linear3,relu,dropout,
                      linear4,relu,dropout,
                      linear5)
model = model.to(device)
model

Sequential(
  (0): Linear(in_features=784, out_features=1024, bias=True)
  (1): ReLU()
  (2): Dropout(p=0.3, inplace=False)
  (3): Linear(in_features=1024, out_features=1024, bias=True)
  (4): ReLU()
  (5): Dropout(p=0.3, inplace=False)
  (6): Linear(in_features=1024, out_features=1024, bias=True)
  (7): ReLU()
  (8): Dropout(p=0.3, inplace=False)
  (9): Linear(in_features=1024, out_features=1024, bias=True)
  (10): ReLU()
  (11): Dropout(p=0.3, inplace=False)
  (12): Linear(in_features=1024, out_features=10, bias=True)
)

In [22]:
loss = nn.CrossEntropyLoss().to(device)
optimizer = optim.Adam(model.parameters(), lr = learning_rate)

In [23]:
total_batch = len(data_loader_train)
model.train() # 주의사항 drop_out = True

for epoch in range(training_epochs):
    
    avg_cost = 0
    
    for X, Y in data_loader_train:
        X_train = X.to(device)
        y_train = Y.to(device)
        
        
        optimizer.zero_grad()
        hypothesis = model(X_train)
        cost = loss(hypothesis,y_train)
        
        cost.backward()
        optimizer.step()
        
        #평균 error 계산
        avg_cost += cost / total_batch
    
    if epoch%10 == 0:
        print('Epoch:','%04d' % (epoch+1), 'cost=','{:.9f}'.format(avg_cost))

Epoch: 0001 cost= 0.459588408
Epoch: 0011 cost= 0.040858511
Epoch: 0021 cost= 0.019399036
Epoch: 0031 cost= 0.014310339
Epoch: 0041 cost= 0.011064983
Epoch: 0051 cost= 0.008651873
Epoch: 0061 cost= 0.008459732
Epoch: 0071 cost= 0.006960549
Epoch: 0081 cost= 0.006152224
Epoch: 0091 cost= 0.006521048


In [24]:
predicted = torch.argmax(hypothesis,1)
accuracy = (predicted == y_train).sum().item() / len(predicted)
accuracy

1.0

# Testing model

In [25]:
with torch.no_grad():
    model.eval()  # 주의사항 (dropout=False)    
    y_test = model(X_test.to(device))
    y_test = torch.argmax(y_test,1)
    y_test = np.array(y_test.cpu())
    print(y_test)

[7 2 1 ... 4 5 6]


# Submit

In [26]:
submit = pd.read_csv('../input/2022-ai-w7p1/submission.csv')
submit

id  Label
0        0      1
1        1      1
2        2      1
3        3      1
4        4      1
...    ...    ...
9995  9995      1
9996  9996      1
9997  9997      1
9998  9998      1
9999  9999      1

[10000 rows x 2 columns]

In [27]:
submit['Label']  = y_test
submit

id  Label
0        0      7
1        1      2
2        2      1
3        3      0
4        4      4
...    ...    ...
9995  9995      2
9996  9996      3
9997  9997      4
9998  9998      5
9999  9999      6

[10000 rows x 2 columns]

In [28]:
submit.to_csv('submit.csv',index=False)